### ISSUE TITLE
很大努力

### ISSUE THREAD

**Issue by Lantianyou** [boism-org/northpole#3]
高考要很大努力，浙大GPA第一要很大努力，伯克利申请要很大努力，转行刷题要很大努力，在键盘另一端克制住情绪要很大努力，接受现实要很大努力，领悟失败要很大努力，
我想问，bobo获得了什么，像徐国xi立党晓笛那样志同道合的朋友吗？像比bobo年轻一点一波波转行申CS，精致利己主义者但没有独立见解的人吗？
bobo想要什么吗？bobo想要钱吗？马云在乎他有多少钱吗？Jeff Bezos在乎他有多少钱吗？显然不是的，钱只是个数字，钱只是成功人士不那么重要的一个特征。bobo想改变浙大，改变中国高等教育体系吗？那bobo为什么不去翻译公开课？bobo为什么不去分享面精？bobo想拒绝割韭菜吗，那bobo为什么不创立个一亩三分地那样的论坛，拒绝留学中介；创立另一个知乎，没有live？
bobo把自己当成什么，老实人吗，不见得吧，成功人士吗，更不是吧？
我在想，bobo甚至宣泄了自己的情绪吗，bobo瞧不起别人约炮瞧不起别人割韭菜瞧不起浙大瞧不起伯克利，甚至瞧不起成功人士。
bobo，为了什么？

**Comment by bboczeng** [comment]
为了全体人类jtzs的那一天

**Comment by Lantianyou** [comment]
bobo能加微信吗？facebook发给兰天游就好。

**Comment by Lantianyou** [comment]
可惜你注销Facebook了

**Comment by Lantianyou** [comment]
> 为了全体人类jtzs的那一天

bobo加个微信好吗，我是Facebook上的兰天游
